### ISSUE TITLE
Wrong number of arguments given to ConfigurationManager

### ISSUE THREAD

**Issue by captainnova** [amorison/qjobs#4]
Hi, I just installed qjobs with
> python3 -m pip install -U --user qjobs
Collecting qjobs
  Downloading qjobs-0.1.1-py3-none-any.whl (9.3 kB)
Collecting setuptools-scm
  Downloading setuptools_scm-4.1.2-py2.py3-none-any.whl (27 kB)
Collecting loam>=0.1.1
  Downloading loam-0.3.1-py3-none-any.whl (13 kB)
Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.6/site-packages (from setuptools-scm->qjobs) (45.2.0)
Collecting toml>=0.9.4
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: setuptools-scm, toml, loam, qjobs
Successfully installed loam-0.3.1 qjobs-0.1.1 setuptools-scm-4.1.2 toml-0.10.2

...but get a startup error:
> Traceback (most recent call last):
  File "/home/me/.local/bin/qjobs", line 5, in <module>
    from qjobs.__main__ import main
  File "/home/me/.local/lib/python3.6/site-packages/qjobs/__init__.py", line 18, in <module>
    conf = ConfigurationManager(config.CONF_DEF, config.CONFIG_FILE)
TypeError: __init__() takes 1 positional argument but 3 were given

Is there a version mismatch between loam and qjobs on PyPI?

Thanks,

Rob

**Comment by amorison** [comment]
Hi Rob,

Sorry about your issue, I haven't been working on this project in a long time and indeed things got out of sync.

Thank you for reporting, I just made a new release (`v0.2.0` that you can get with the same command you used to install `qjobs`) that should fix this issue. Please let me know if this works for you.

Note however that qjobs was written for a cluster using the SGE scheduler and adding support for another scheduler will take me some time but I have also interest in that as I no longer use SGE and kinda just forgot about `qjobs`...

Hopefully I will have more time to maintain it properly in the coming weeks, let me know if you run into other issues. Having an user will definitely motivate me in improving this tool!

**Comment by captainnova** [comment]
Thanks, it works now.

We are (still) using OGE, which is very similar to SGE.
